version: "3.2"
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: "rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 30s
            retries: 3
        networks:
            - rabbitmq_go_net

    producer_consumer:
        build:
            context: ./
            dockerfile: Dockerfile
            target: producer_consumer
        command:
            [
                "uvicorn",
                "src.producer_consumer.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "--reload",
            ]
        hostname: producer_consumer
        container_name: producer_consumer
        depends_on:
            rabbitmq:
                condition: service_healthy
        env_file:
            - .env
        environment:
            PYTHONPATH: src
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        networks:
            - rabbitmq_go_net

    consumer:
        build:
            context: ./
            dockerfile: Dockerfile
        command: python -m src.consumer.main
        container_name: consumer
        depends_on:
            - producer_consumer
        env_file:
            - .env
        environment:
            PYTHONPATH: src
            LOGLEVEL: INFO
        ports:
            - "8001:8001"
        volumes:
            - ./:/app
        networks:
            - rabbitmq_go_net

networks:
    rabbitmq_go_net:
        driver: bridge
